### PR TITLE
Lein 2 Compatibility

### PR DESCRIPTION
**Pull request by seancorfield**
First pass at compatibility with Leiningen 2.
- Removes dependency on old contrib (throwf).
- Accounts for Leiningen namespace reorganization.
- Updates eval-in-project to match new (restricted) API.

Limitations:
- Can no longer spawn a background process directly since the ant-based callback has been removed from Leiningen (the .setSpawn call that lein-daemon used to do).
- Usage is now: `lein daemon start :process &` or `nohup lein daemon start :process &`
- `lein daemon stop :process` correctly kills the process but "clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 143}" is displayed

### CODE REVIEW

**Comment by arohner** [comment]
I don't like that the process has to be called with '&'. In addition to being ugly, that doesn't really daemonize unless you nohup, and close stdin & stdout. 

Have you looked at lein trampoline? It looks like it's possible to piggyback on trampoline, by writing our own trampoline file that will be picked up by the lein the-bash-command. I can try to look into that this week if you're not interested.

**Comment by seancorfield** [comment]
I started looking at trampoline but after chatting with Phil I couldn't see how to get it to spawn a new process in the background. So, yes, feel free to try.

I have what I need now (in my own 0.5.0-SNAPSHOT on Clojars) which was mainly the PID file writing and the check / stop functions. Obviously having the start function actually spawn a new process would be preferable so I'm keep tracking what changes you make in that area.

**Comment by eslick** [comment]
Any update on retooling lein-daemon to use trampoline?  I'm building a set of chef scripts to launch a set of clojure apps on an AWS cluster and a simple solution for daemonizing noir apps would be really helpful!  Thanks, Ian

**Comment by arohner** [comment]
Sorry for the delay. I have working code on the `lein2` branch, but until the lein release _after_ 2.0.0-preview10,  it requires using my own lein script: https://github.com/arohner/leiningen/blob/master/bin/lein

I'll make an official release as soon as there's an another lein2 official release.

**Comment by seancorfield** [comment]
Thanx for the update on this. I look forward to trying it out - to replace my hacked together version of lein-daemon that we're using right now!

**Comment by eslick** [comment]
FYI - I ended up using upstart and with lein run which has been working nicely.  Here's a chef template for the upstart config file...

---

# Upstart script for experiment via Lein

description "Start and stop experiment system using lein"
version "1.0"
author "Ian Eslick"

# Configuration

# expect fork

start on startup
start on runlevel [2345]
stop on runlevel [!2345]

chdir /home/ubuntu/<%= node['experiment']['site']['tag'] %>/current
setuid ubuntu
exec lein trampoline run <%= node['experiment']['site']['mode'] %> > out.log 2>&1

**Comment by arohner** [comment]
Resolved in 0.5

**Pull request closed without merging**
